#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
WeChat Publishing Configuration
Auto-generated by create_default_cover.py
"""

# Default cover image media_id
DEFAULT_COVER_MEDIA_ID = "WOr7ZIAYNpvYmON1V3ZQwcJJM5-5tgg8B2WMeN-oQF6R3PSE5lrtwOhwvcAOc_ZC"

# WeChat Official Account Credentials
APPID = "wxf9400829e3405317"
APPSECRET = "a6800143c01df2e73121c631cac4ec32"
